version: "2.1"
services:
  metricshub:
    build: .        # for image we will use `image: sentrysoftware/metricshub`
    container_name: metricshub
    ports:
      - 8888:8888   # OpenTelemetry Collector Exporter
      - 4317:4317   # OpenTelemetry Collector gRPC Receiver
      - 13133:13133 # OpenTelemetry Collector HealthCheck
    volumes:
      - ./lib/logs:/opt/metricshub/lib/logs
      - ./lib/config:/opt/metricshub/lib/config
      - ./lib/otel:/opt/metricshub/lib/otel
    restart: unless-stopped
    