name: Documentation
description: Use this template to request updates to the MetricsHub documentation.
labels: ["documentation", "needs_triage"]
body:
  - type: textarea
    attributes:
      label: Documentation updates
      description: Please provide which part of the documentation needs to be updated
      value: |
        ## Documentation section(s)
        1. Introduction
        2. Release Notes
        3. Installation
        4. Upgrade
        5. Configuration
        6. Integration
        7. Datadog
        8. Prometheus
        9. Grafana
        10. BMC Helix
        11. AI Agents Integration
        11. Troubleshooting
        12. CLI

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
