loggerLevel: debug
targets:

  - target:
      hostname: dev-hv-01
      type: windows
    wmi:
      timeout: 120
      username: dev-hv-01\patrol
      password: patrol
    selectedConnectors: [LibreHardwareMonitor]