logging:
  pattern:
    console: ''
spring:
  main:
    banner-mode: "off"
project:
  name: "@project.name@"
  version: "@project.version@"
buildNumber: "@buildNumber@"
timestamp: "@timestamp@"
hcVersion: "@hardware-connectors.version@"