config:
server:
  port: 8080
project:
  name: "@project.name@"
  version: "@project.version@"
buildNumber: "@buildNumber@"
buildDate: "@timestamp@"
hcVersion: "@hardware-connectors.version@"
otelVersion: "@otelVersion@"
spring:
  main:
    banner-mode: "off"
    web-application-type: none
grpc: https://localhost:4317