# MetricsHub Configuration

# Default logger level
loggerLevel: error

# Internal collect interval
collectPeriod: 1m

# Internal OpenTelemetry SDK configuration
otel:
  # OpenTelemetry SDK Autoconfigure properties
  # https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure
  # MetricsHub Default configuration
  # otel.metrics.exporter: otlp
  # otel.logs.exporter: otlp
  # otel.exporter.otlp.metrics.endpoint: http://localhost:4317
  # otel.exporter.otlp.logs.endpoint: http://localhost:4317
  # otel.exporter.otlp.metrics.protocol: grpc # Options include grpc and http/protobuf
  # otel.exporter.otlp.logs.protocol: grpc # Options include grpc and http/protobuf
  
# Simple resource configuration
resources:
  localhost:
    attributes:
      host.name: localhost
      host.type: windows
    protocols:
      wmi:
        timeout: 120

  #═══════════════════════════════════════════════════
  # SNMP v1 protocol configuration
  #═══════════════════════════════════════════════════

  # server-01:
  #   attributes:
  #     host.name: server-01
  #     host.type: linux
  #   protocols:
  #     snmp:
  #       version: v1
  #       community: public
  #       port: 161
  #       timeout: 120

# Resource Groups configuration
resourceGroups:

  # Resource Group identifier
  data-center-1:

     # Adds additional static attributes to all the resources in the group
    attributes:
      site: data center 1 # Customize this value with your own site naming convention. (Dedicating 1 collector to 1 site is a good practice.)

    # Adds additional static metrics to all the resources in the group.
    metrics:
      hw.site.carbon_intensity: 230 # in g/kWh
      # Carbon dioxide produced per kilowatt-hour.
      # The average is 230g/kWh for Europe.
      # The average is 309g/kWh for Texas, USA.
      # The average is 40g/kWh for Ontario, Canada.
      # The average is 712g/kWh for Queensland, Australia.
      # Source: https://app.electricitymap.org/map

      hw.site.electricity_cost: 0.12 # in $/kWh
      # Electricity cost per kilowatt-hour. 
      # The average is $0.12/kWh for non-household in Europe.
      # The average is $0.159/kWh for non-household in the USA.
      # The average is $0.117/kWh for non-household in Canada.
      # The average is $0.225/kWh for non-household in Australia.
      # Source: https://www.globalpetrolprices.com/electricity_prices/

      hw.site.pue: 1.8
      # Power Usage Effectiveness. A ratio describing how efficiently a computer data center uses energy. The ideal ratio is 1.

    # Some resource templates can be found below:
    resources:

      #═══════════════════════════════════════════════════
      # IPMI protocol configuration    
      #═══════════════════════════════════════════════════

      # server-1:
      #   attributes:
      #     host.name: server-1
      #     host.type: oob
      #   protocols:
      #     ipmi:
      #       username: username
      #       password: password
      #       timeout: 120

      #═══════════════════════════════════════════════════
      # WMI protocol configuration     
      #═══════════════════════════════════════════════════

      # server-2:
      #   attributes:
      #     host.name: server-2
      #     host.type: win
      #   protocols:
      #     wmi:
      #       timeout: 120

      #═══════════════════════════════════════════════════
      # WMI protocol configuration with credentials      
      #═══════════════════════════════════════════════════

      # server-3:
      #   attributes:
      #     host.name: server-3
      #     host.type: win
      #   protocols:
      #     wmi:
      #       username: server-3\username
      #       password: password
      #       timeout: 120

      #═══════════════════════════════════════════════════
      # SNMP v1 protocol configuration
      #═══════════════════════════════════════════════════

      # server-4:
      #   attributes:
      #     host.name: server-4
      #     host.type: linux
      #   protocols:
      #     snmp:
      #       version: v1
      #       community: public
      #       port: 161
      #       timeout: 120
      #   connectors: [ -SunF15K ]

      #═══════════════════════════════════════════════════
      # SNMP v2c protocol configuration
      #═══════════════════════════════════════════════════

      # server-5:
      #   attributes:
      #     host.name: server-5
      #     host.type: oob
      #   protocols:
      #     snmp:
      #       version: v2c
      #       community: public
      #       port: 161
      #       timeout: 120

      #═══════════════════════════════════════════════════
      # WBEM protocol configuration    
      #═══════════════════════════════════════════════════

      # server-7:
      #   attributes:
      #     host.name: server-7
      #     host.type: storage
      #   protocols:
      #     wbem:
      #       protocol: https
      #       port: 5989
      #       timeout: 120
      #       username: admin
      #       password: password

      #═══════════════════════════════════════════════════
      # HTTP protocol configuration    
      #═══════════════════════════════════════════════════

      # server-8:
      #   attributes:
      #     host.name: server-8
      #     host.type: storage
      #   protocols:
      #     http:
      #       https: true
      #       port: 443
      #       username: username
      #       password: password
      #   connectors:
      #   - +PureStorageREST

      #═══════════════════════════════════════════════════
      # SSH protocol configuration     
      #═══════════════════════════════════════════════════

      # server-9:
      #   attributes:
      #     host.name: server-9
      #     host.type: linux
      #   protocols:
      #     ssh:
      #       timeout: 120
      #       useSudo: true
      #       useSudoCommands: [ isi, isi_for_array ]
      #       sudoCommand: sudo
      #       username: myusername
      #       password: mypwd
      #       privateKey: /tmp/ssh-key.txt

      #═══════════════════════════════════════════════════
      # OSCommand configuration        
      #═══════════════════════════════════════════════════

      # server-10:
      #   attributes:
      #     host.name: server-10
      #     host.type: linux
      #   protocols:
      #     osCommand:
      #       timeout: 120
      #       useSudo: true
      #       useSudoCommands: [ ]
      #       sudoCommand: sudo

      #═══════════════════════════════════════════════════
      # WinRM configuration            
      #═══════════════════════════════════════════════════

      # server-11:
      #   attributes:
      #     host.name: server-11
      #     host.type: win
      #   protocols:
      #     winrm:
      #       timeout: 120
      #       username: myusername
      #       password: mypwd
      #       port: 5985
      #       protocol: http
      #       authentications: [ntlm, kerberos]

      #═══════════════════════════════════════════════════
      # vCenter WBEM configuration            
      #═══════════════════════════════════════════════════

      # server-12:
      #   attributes:
      #     host.name: server-12
      #     host.type: oob
      #   protocols:
      #     wbem:
      #       protocol: https
      #       port: 5989
      #       timeout: 120
      #       username: admin
      #       password: password
      #       vcenter: server-vcenter

      #═══════════════════════════════════════════════════
      # Host Group SNMP v1 protocol configuration
      #═══════════════════════════════════════════════════

      # group-1:
      #   attributes:
      #     host.names: [server-13, server-14, server-15]
      #     host.type: linux
      #   protocols:
      #     snmp:
      #       version: v1
      #       community: public
      #       port: 161
      #       timeout: 120
