version: "2.1"
services:
  metricshub:
    build: .        # for image we will use `image: metricshub/metricshub-community`
    container_name: metricshub
    volumes:
      - ./lib/logs:/opt/metricshub/lib/logs
      - ./lib/config:/opt/metricshub/lib/config
    restart: unless-stopped
