config: ''
server:
  port: 8080
project:
  name: "@project.name@"
  version: "@project.version@"
buildNumber: "@buildNumber@"
timestamp: "@timestamp@"
hcVersion: "@hardware-connectors.version@"
spring:
  main:
    banner-mode: "off"