name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build-main:

    permissions:
      contents: write
      packages: write

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-latest, rocky-latest ]

    steps:

    - name: Set up Maven
      if: ${{ matrix.os == 'rocky-latest' }}
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.6

    - name: Install gcc-multilib
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Set up Maven settings.xml on ${{ matrix.os }}
      uses: s4u/maven-settings-action@v3.0.0
      with:
        repositories: '[{"id":"github","name":"MetricsHub JRE Builder","url":"https://maven.pkg.github.com/sentrysoftware/metricshub-jre-builder","snapshots":{"enabled":true},"releases":{"enabled":true}}]'
        sonatypeSnapshots: true

    - name: Build with Maven on ${{ matrix.os }}
      run: mvn -B -U verify --file pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload Debian Artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      with:
        name: debian-package
        path: ./metricshub-debian/target/*.deb

    - name: Upload RPM Artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.os == 'rocky-latest' }}
      with:
        name: rpm-package
        path: ./metricshub-rhel/target/*.rpm

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.os == 'windows-latest' }}
      with:
        name: windows-package
        path: ./metricshub-windows/target/*.msi

    - name: Upload Site Artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      with:
        name: site
        path: ./metricshub-doc/target/metricshub-doc-*-site.jar

    - name: Upload Docker Artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      with:
        name: docker-package
        path: ./metricshub-debian/target/*-docker.tar.gz
