name: Deploy

on:
  push:
    branches: [ "main" ]

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build-main:

    permissions:
      contents: write
      packages: write

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:

    - name: Install gcc-multilib
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib

    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Set up Maven settings.xml on ${{ matrix.os }}
      uses: s4u/maven-settings-action@v3.1.0
      with:
        repositories: >-
          [
            {
              "id": "github",
              "name": "MetricsHub JRE Builder",
              "url": "https://maven.pkg.github.com/metricshub/metricshub-jre-builder",
              "snapshots": { "enabled": true },
              "releases": { "enabled": true }
            },
            {
              "id": "central-snapshots",
              "name": "Maven Repository Switchboard",
              "url": "https://central.sonatype.com/repository/maven-snapshots",
              "snapshots": { "enabled": true },
              "releases": { "enabled": false }
            }
          ]
        servers: '[{"id": "central", "username": "${env.MAVEN_CENTRAL_USERNAME}", "password": "${env.MAVEN_CENTRAL_TOKEN}"}]'
        sonatypeSnapshots: true

    - name: Build with Maven on ${{ matrix.os }}
      run: mvn -B -U deploy --file pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}

    - name: Get version
      run: |
            metricshub_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "MetricsHub version ${metricshub_version}"
            echo "metricshub_version=$metricshub_version" >> $GITHUB_ENV

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.os == 'ubuntu-latest' }}
      with:
        name: metricshub-community-linux-package-${{ env.metricshub_version }}
        path: ./metricshub-community-linux/target/metricshub-community-linux-${{ env.metricshub_version }}.tar.gz

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.os == 'windows-latest' }}
      with:
        name: metricshub-community-windows-package-${{ env.metricshub_version }}
        path: ./metricshub-community-windows/target/metricshub-community-windows-${{ env.metricshub_version }}.zip

    - name: Upload Site Artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.os == 'ubuntu-latest' }}
      with:
        name: metricshub-site-${{ env.metricshub_version }}
        path: ./metricshub-doc/target/metricshub-doc-${{ env.metricshub_version }}-site.jar

    - name: Upload Docker Artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.os == 'ubuntu-latest' }}
      with:
        name: metricshub-community-docker-package-${{ env.metricshub_version }}
        path: ./metricshub-community-linux/target/metricshub-community-linux-${{ env.metricshub_version }}-docker.tar.gz
 